### ISSUE TITLE
Negative Durability

### ISSUE THREAD

**Issue by fahlur** [Steel-Dev/ItemQualities#13]
I noticed a tool while testing ended up having negative durability. 

https://imgur.com/XiqS4Kz

I was actually testing about something some players mentioned..
Also a couple players talked about their tool nearly breaking then automatically almost full repairing.

is this suppose to occur? They did have the godly quality. But I couldnt recreate it due to the above thing I ran across while testing xD

**Comment by Steel-Dev** [comment]
The durability display does not reflect the custom durability system, as that is impossible, so with this plugin the durability display is not accurate, but the green bar on the item in the inventory is accurate.

Though, it going into negatives is not intended. Thanks!

and the repairing issue.. I think I already fixed this, what version of the plugin are you on? I fixed it back in version 1.0.5. In my testing, since that patch, I have not been able to recreate that issue.

**Comment by Steel-Dev** [comment]
I've rewritten my custom durability system, or.. more so tweaked it, found many issues and fixed them.. So thank you for raising this issue or I might not have found them lmao

Fixes will be coming in 1.0.7!

**Comment by fahlur** [comment]
Im currently using 1.0.6 so I can get that answer in for you. :)

1 person was with an Axe and the other was with.. uhg I think it was a fishing rod.

**Comment by Steel-Dev** [comment]
Strange, hopefully it will be fixed with my tweaks to my durability system. Can't really say for sure, though, since I'm also unable to recreate it what so ever.

1.0.7 is huge right now, along with so many changes and fixes, and one massive addition. I'm hoping to release it soon.

**Comment by fahlur** [comment]
After updating I will keep my eyes out with some testing and such, also I have informed them if it happens again to give me the clearest info that can give me that led to it, as well preferably a timestamp so I can see if a log showed at all in case as well.

**Comment by kvakkvak** [comment]
Also happend to me with Axe and Trident that they healed to full hp

**Comment by fahlur** [comment]
thats alright, I was just told my a staff member on my server when they got done "netheriting up their gear"
I presume they mean converting their stuff to netherite, all the enchants disappeared and the quality changed.

im asking them more questions to clarify the situation with it. Because I want this successful and I want to make sure things get caught for our friend here :). So its noted here, but once I get proper clarification and able to test it (hopefully recreate it) ill make a ticket for it.
=

**Comment by Steel-Dev** [comment]
I know for a fact I made it keep the same quality when upgrading to netherite. Why the hell is it I test and test something for hours straight, fixing it, unable to recreate it again - then it just magically breaks for other people when it shouldn't? :T grr

**Comment by Steel-Dev** [comment]
Oh wait, do you have applyQualityOnCraft enabled?

If so, Smithing counts as crafting, so that's why the Quality was rerolled. I wrote it like so;

quality on craft disabled: Result of smithing will get the same quality as the input item
quality on craft enabled: Result of smithing will get its quality rerolled - since you're technically still crafting, the idea I had in mind is your character either just made a bad quality upgrade, or a better quality one. 

I could remove this, since it seems to be causing confusion.

**Comment by Steel-Dev** [comment]
Okay I have rewritten the Quality application for Smithing. As well as added a new config option to toggle whether the result items Quality will be rerolled or not. (true - reroll, false - result will get the same quality as the input item)

The enchantments not carrying over has also been fixed up.

**Comment by Steel-Dev** [comment]
Fixed in release 1.1.0!
